name: Build and Package

on:
  workflow_dispatch: 
    inputs:
      source_branch:
        description: 'The source branch or ref to build from'
        default: 'main'
        required: true

jobs:
  release:
    environment: OSSign
    runs-on: win2k25-xl
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repo: 'Beaver-Notes/Beaver-Notes'
          ref: ${{ github.event.inputs.source_branch }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: build Vite bundles
        run: yarn build

      - name: Build and conditionally publish Electron app
        shell: bash
        env:
          AST_VAULT: ${{ secrets.AST_VAULT }}
          AST_CERT: ${{ secrets.AST_CERT }}
          AST_IDENT: ${{ secrets.AST_IDENT }}
          AST_SECRET: ${{ secrets.AST_SECRET }}
          AST_TENANT: ${{ secrets.AST_TENANT }}
          AST_TIMESTAMP: ${{ secrets.AST_TIMESTAMP }}
          AST_TD: ${{ secrets.AST_TD }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn electron-builder build --config electron-builder.config.cjs --win

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Beaver-Notes-Windows
          path: dist/*
